apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        image: 401704305923.dkr.ecr.ap-southeast-2.amazonaws.com/products-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        # Add more environment variables if needed (e.g., DB credentials)

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: products-service
